[project]
name = "unidocs"
version = "2.1.0" # change this in src/ui/settings_dialog.py too !
description = "Document management and productivity application"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Lukas Buschauer", email = "lukas.buschauer@gmail.com" }
]
dependencies = [
    "flet>=0.84.0",
    "watchdog>=6.0.0",
    "platformdirs>=4.9.6",
]

[dependency-groups]
dev = [
    "flet-cli>=0.84.0",
    "flet-desktop>=0.84.0",
    "flet-web>=0.84.0",
]

[tool.flet]
desktop_flavor = "light"    # Change to "full" to use flet-audio and flet-video
org = "de.buschauermedia"
product = "unidocs"
company = "Buschauer Media"
copyright = "Copyright (C) 2026 Buschauer Media"

[tool.flet.app]
path = "src"
